<?php
/**
 * @file
 * CultureFeed Messages adds the ability to send messages to other users.
 */

/**
 * Implements hook_theme().
 */
function culturefeed_social_theme() {

  $path = drupal_get_path('module', 'culturefeed_social') . '/theme';

  return array(
    'culturefeed_messages_message_list'=> array(
      'variables' => array(
        'messages' => NULL,
      ),
      'template' => 'culturefeed-messages-message-list',
      'path' => $path,
      'file' => 'theme.inc',
    ),
    'culturefeed_messages_message_list_item'=> array(
      'variables' => array(
        'message' => NULL,
      ),
      'template' => 'culturefeed-messages-message-list-item',
      'path' => $path,
      'file' => 'theme.inc',
    ),
  );

}

/**
 * Implements hook_menu().
 */
function culturefeed_messages_menu() {

  $items = array();

  $items['culturefeed/messages/%culturefeed_messages_message'] = array(
    'title callback' => FALSE,
    'title' => 'Mijn berichten',
    'page callback' => 'culturefeed_messages_message',
    'access callback' => 'culturefeed_is_culturefeed_user',
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  if (module_exists('culturefeed_pages')) {
    $items['pages/%culturefeed_pages_page/messages/new'] = array(
      'title callback' => FALSE,
      'title' => 'Berichten',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('culturefeed_messages_new_message_form', 1),
      'access callback' => 'culturefeed_pages_edit_page_access',
      'access arguments' => array(1),
      'type' => MENU_CALLBACK,
      'file' => 'includes/pages.inc',
    );
  }

  return $items;

}

/**
 * Implements hook_block_info().
 */
function culturefeed_pages_block_info() {

  $blocks = array();

  $blocks['inbox'] = array(
    'info' => t('Messages: inbox'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;

}
/**
 * Implements hook_block_view().
 */
function culturefeed_pages_block_view($delta) {

  module_load_include('inc', 'culturefeed_messages', 'includes/blocks');

  switch ($delta) {

    case 'inbox':
      return culturefeed_messages_block_inbox();

  }

}

/**
 * Load a message by id.
 * @param string $message_id
 *   ID of message to load.
 */
function culturefeed_messages_message_load($message_id) {

}