<?php

/**
 * @file
 * Contains culturefeed_mss_151.module.
 */

/**
 * Implements hook_culturefeed_search_service_created().
 */
function culturefeed_cdb_upgrade_culturefeed_search_service_created($service) {

  /** @var \CultuurNet\Search\Guzzle\Service $service */
  // Temporary workaround to set CDB to 3.3
  $client_factory = $service->getHttpClientFactory();
  $client_factory->addSubscriber(new CdbEventSubscriber());
  $service->setHttpClientFactory($client_factory);

}

/**
 * Returns the version number.
 */
function culturefeed_cdb_upgrade_get_schema_version_number() {

  $schema_name = CultureFeed_Cdb_Default::CDB_SCHEME_URL;
  $pattern = '/(http:\/\/www.cultuurdatabank.com\/XMLSchema\/CdbXSD\/)(.*)(\/FINAL)/';
  $matches = array();
  preg_match($pattern, $schema_name, $matches);
  return $matches[2];

}