<?php
/**
 * @file
 * CultureFeed Calendar allows users to manage their own activities in a calendar.
 */

require_once 'includes/helpers.inc';

/**
 * Implements hook_menu().
 */
function culturefeed_calendar_menu() {

  $items = array();

  $items['culturefeed/calendar'] = array(
    'title' => t('My Calendar'),
    'page callback' => 'culturefeed_calendar_page_my_activities',
    'access arguments' => array('access content'),
    'file' => 'includes/pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['culturefeed/calendar/add/%culturefeed_agenda_event/%'] = array(
    'title' => t('Add to calendar'),
    'page callback' => 'culturefeed_calendar_add_to_calendar',
    'page arguments' => array(3, 4),
    'access arguments' => array('access content'),
    'file' => 'includes/pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['culturefeed/calendar/add-cookie-to-calendar'] = array(
    'title' => t('Add cookie events to calendar'),
    'page callback' => 'culturefeed_calendar_add_cookie_to_calendar',
    'access arguments' => array('access content'),
    'file' => 'includes/pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function culturefeed_calendar_theme() {

  $items = array();

  $path = drupal_get_path('module', 'culturefeed_calendar') . '/theme';

  $items['culturefeed_calendar_button'] = array(
    'path' => $path,
    'file' => 'theme.inc',
    'template' => 'culturefeed-calendar-button',
  );
  $items['culturefeed_calendar_total_activities_profile_box_item'] = array(
    'variables' => array('total' => 0),
    'path' => $path,
    'file' => 'theme.inc',
  );
  $items['culturefeed_calendar_activity_summary'] = array(
    'path' => $path,
    'file' => 'theme.inc',
    'template' => 'culturefeed-calendar-activity-summary',
    'variables' => array(
      'activity' => NULL
    ),
  );
  $items['culturefeed_calendar_activity_mini'] = array(
    'path' => $path,
    'file' => 'theme.inc',
    'template' => 'culturefeed-calendar-activity-mini',
    'variables' => array(
      'activity' => NULL
    ),
  );
  $items['culturefeed_calendar_activities_going'] = array(
    'path' => $path,
    'file' => 'theme.inc',
    'template' => 'culturefeed-calendar-activities-going',
    'variables' => array(
      'activities' => NULL
    ),
  );
  $items['culturefeed_calendar_activities_liked'] = array(
    'path' => $path,
    'file' => 'theme.inc',
    'template' => 'culturefeed-calendar-activities-liked',
    'variables' => array(
      'activities' => NULL
    ),
  );
  $items['culturefeed_calendar_nav_months'] = array(
    'path' => $path,
    'file' => 'theme.inc',
    'template' => 'culturefeed-calendar-nav-months',
    'variables' => array(
      'activities' => NULL
    ),
  );

  return $items;

}

/**
 * Implements hook_culturefeed_ui_profile_box_main_items().
 */
function culturefeed_calendar_culturefeed_ui_profile_box_main_items() {

  $items = array();

  $items['activities'] = array(
    'data' => theme('culturefeed_calendar_total_activities_profile_box_item', array(
      'total' => culturefeed_calendar_get_total_unread_activities(),
    )),
    'class' => 'activities',
    'weight' => -10,
  );

  return $items;

}

/**
 * Implements hook_culturefeed_ui_anonymous_profile_box_main_items().
 */
function culturefeed_calendar_culturefeed_ui_anonymous_profile_box_main_items() {

  $items = array();

  $items['activities'] = array(
    'data' => theme('culturefeed_calendar_total_activities_profile_box_item', array(
      'total' => culturefeed_calendar_get_total_unread_activities(),
    )),
    'class' => 'activities',
    'weight' => -10,
  );

  return $items;

}