<?php

/**
 * @file
 * Contains the culturefeed date control module.
 */

// Includes.
require_once 'form_element/date_control.inc';

/**
 * Ajax callback for the date control element.
 */
function culturefeed_date_control_ajax_callback($form, $form_state) {

  // Buttons are on different levels inside the element.  Find the correct
  // parent by starting from the deepest element.
  $parents = array_reverse($form_state['triggering_element']['#array_parents']);
  foreach ($parents as $element) {
    array_shift($parents);
    if ($element == 'date_control') {
      break;
    }
  }
  $parents = array_reverse($parents);
  return drupal_array_get_nested_value($form, $parents);

}

/**
 * Implements hook_element_info().
 */
function culturefeed_date_control_element_info() {
  return array(
    'culturefeed_date_control' => array(
      '#input' => TRUE,
      '#process' => array('culturefeed_date_control_process_element'),
    ),
  );
}

/**
 * Implements hook_element_info_alter().
 */
function culturefeed_date_control_element_info_alter(&$types) {
  if (isset($types['date_popup'])) {
    $types['date_popup']['#after_build'][] = 'culturefeed_date_control_element_date_popup_after_build';
  }
}

/**
 * Adds a span element for a calendar icon on date popup fields.
 */
function culturefeed_date_control_element_date_popup_after_build($element, $form_state) {
  if (isset($element['date']) && isset($element['#icon']) && $element['#icon']) {
    $element['date']['#suffix'] = "<span class=\"ui-icon ui-icon-calendar\"></span>";
  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function culturefeed_date_control_theme() {

  return array(
    'culturefeed_date_control_timestamps_table' => array(
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'culturefeed_date_control') . '/theme',
      'render element' => 'form',
    ),
  );

}
