<?php
/**
 * @file
 * Module file for all functionality for CultureFeed Search.
 */

// Default API location. Can be overriden in settings form.
define('CULTUREFEED_SEARCH_API_LOCATION', 'http://acc.uitid.be/uitid/rest/searchv2/');
define('CULTUREFEED_SEARCH_CACHE_EXPIRES', 3600);

// Default cdb schema version.  Can be overridden in settings form.
define('CULTUREFEED_SEARCH_CDB_DEFAULT_VERSION', '3.2');

// Default proximity search range.
define('CULTUREFEED_SEARCH_DEFAULT_PROXIMITY_RANGE', 20);

module_load_include('inc', 'culturefeed_search', 'includes/helpers');

/**
 * Implements hook_culturefeed_search_service_created().
 *
 * @param \CultuurNet\Search\Guzzle\Service $service
 *   The service.
 */
function culturefeed_search_culturefeed_search_service_created($service) {

  // Temporary workaround to set CDB to 3.3
  $version = variable_get('culturefeed_search_cdb_version', CULTUREFEED_SEARCH_CDB_DEFAULT_VERSION);

  if (version_compare($version, '3.3', '>=')) {

    $client_factory = $service->getHttpClientFactory();
    $client_factory->addSubscriber(new CdbEventSubscriber());
    $service->setHttpClientFactory($client_factory);

  }

}

/**
 * Returns the cdb schema version number.
 */
function culturefeed_search_get_cdb_schema_version_number() {

  $schema_name = CultureFeed_Cdb_Default::CDB_SCHEME_URL;
  $pattern = '/(http:\/\/www.cultuurdatabank.com\/XMLSchema\/CdbXSD\/)(.*)(\/FINAL)/';
  $matches = array();
  preg_match($pattern, $schema_name, $matches);
  return $matches[2];

}

/**
 * Implements hook_init().
 */
function culturefeed_search_init() {

  // Set noindex metatag when Search API location points to acceptance.
  if (culturefeed_search_acceptance_mode()) {
    culturefeed_search_set_noindex_metatag();
  }
}

/**
 * Implements hook_menu().
 */
function culturefeed_search_menu() {

  $items['admin/config/culturefeed/search'] = array(
    'title' => 'CultureFeed Search',
    'description' => 'Change CultureFeed Search API setting like API Appliction key, location, ...',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('culturefeed_search_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.inc',
  );

  // Autocomplete path for suggestions.
  $items['autocomplete/culturefeed/suggestions'] = array(
    'title' => 'Culturefeed suggestions autocomplete',
    'page callback' => 'culturefeed_search_suggestions_autocomplete_page',
    'page arguments' => array(3, FALSE, NULL, FALSE),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  // Autocomplete path for actor
  $items['autocomplete/culturefeed/actor-suggestions'] = array(
    'title' => 'Culturefeed suggestions autocomplete',
    'page callback' => 'culturefeed_search_suggestions_autocomplete_page',
    'page arguments' => array(3, FALSE, 'actor', FALSE),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );
  
  // Autocomplete path for all actors from production (temporary workaround for PWK-213)
  $items['autocomplete/culturefeed/actor-suggestions/all'] = array(
    'title' => 'Culturefeed suggestions autocomplete',
    'page callback' => 'culturefeed_search_suggestions_autocomplete_page',
    'page arguments' => array(4, FALSE, 'actor', TRUE),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  // Autocomplete path for region suggestions.
  $items['autocomplete/culturefeed/region-suggestion'] = array(
    'page callback' => 'culturefeed_search_region_suggestion_autocomplete_page',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  // Autocomplete for city and region suggestions
  $items['autocomplete/culturefeed/city-suggestion'] = array(
    'page callback' => 'culturefeed_search_city_suggestion_autocomplete_page',
    'page arguments' => array(3, FALSE),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );
  $items['autocomplete/culturefeed/city-region-suggestion'] = array(
    'page callback' => 'culturefeed_search_city_suggestion_autocomplete_page',
    'page arguments' => array(3, TRUE),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  return $items;

}

/**
 * Implements hook_flush_caches().
 */
function culturefeed_search_flush_caches() {
  return array('cache_culturefeed_search');
}

/**
 * Clears all cache for culturefeed search results and related activity.
 */
function _culturefeed_search_flush_caches($search_only = FALSE) {
  cache_clear_all('culturefeed:', 'cache_culturefeed_search', TRUE);
  if (!$search_only) {
    cache_clear_all('culturefeed:', 'cache_culturefeed', TRUE);
  }
}

/**
 * Implements hook_form_alter().
 */
function culturefeed_search_form_system_performance_settings_alter(&$form, $form_state) {

  // We want our stuff before the clear cache fieldset and button.
  $form['buttons']['#weight'] = 3;
  $form['clear_cache']['#weight'] = 2;

  // Adding API cache settings to the performance settings form.
  $form['culturefeed_search_cache'] = array(
    '#type' => 'fieldset',
    '#title' => t('CultureFeed Search cache'),
    '#weight' => 1,
    '#description' => t('Enabling the CultureFeed Search cache will cache some parsed results of requests to the CultureFeed API. This will reduce the number of requests made directly to the API service.'),
  );

  $form['culturefeed_search_cache']['culturefeed_search_cache_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Cache API requests'),
    '#default_value' => variable_get('culturefeed_search_cache_enabled', FALSE),
  );

  $form['culturefeed_search_cache']['culturefeed_search_cache_flush'] = array(
    '#type' => 'submit',
    '#value' => t('Flush the Culturefeed search cache'),
    '#submit' => array('culturefeed_search_cache_flush_submit'),
  );

  $period = array(0 => '<' . t('none') . '>') + drupal_map_assoc(array(0, 60, 180, 300, 600, 900, 1800, 2700, 3600, 10800, 21600, 32400, 43200, 86400, 86400 * 2, 86400 * 5, 86400 * 7, 86400 * 14, 86400 * 28), 'format_interval');

}

/**
 * Submit handler to flush the culturefeed search cache.
 * @param type $form
 * @param type $form_state
 */
function culturefeed_search_cache_flush_submit($form, $form_state) {
  _culturefeed_search_flush_caches();

}

