<?php

/**
 * @file
 * Implementation of the cultuurnet/data-validation library.
 */

require_once 'culturefeed_data_validation.helpers.inc';

/**
 * Implements hook_menu().
 */
function culturefeed_data_validation_menu() {
  $items = array();

  // Configuration page.
  $items['admin/config/culturefeed/data-validation'] = array(
    'title' => 'CultureFeed Data Validation',
    'description' => 'CultureFeed Data Validation settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('culturefeed_data_validation_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'culturefeed_data_validation.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_form_{culturefeed_mailing_newsletter_block_form}_alter().
 */
function culturefeed_data_validation_form_culturefeed_mailing_newsletter_block_form_alter(&$form, $form_state) {
  $form['#validate'][] = 'culturefeed_data_validation_newsletter_block_form_validate';
}

/**
 * Validate the email address using the datavalidation service.
 */
function culturefeed_data_validation_newsletter_block_form_validate($form, &$form_state) {
  try {

    $datavalidationClient = _culturefeed_data_validation_get_datavalidation_client();
    $response = $datavalidationClient->validateEmail($form_state['values']['mail']);
    if ($response && (!$response->isOK() || $response->getGrade() === 'F') ) {
      form_set_error('mail', t('The provided email address is invalid.'));
    }
  }
  catch (Exception $e) {
    // Show no error here.
  }
}