<?php

/**
 * @file
 * Module file for Culturefeed uitpas.
 */

require_once 'culturefeed_uitpas.blocks.inc';
require_once 'culturefeed_uitpas.forms.inc';
require_once 'culturefeed_uitpas.helpers.inc';
require_once 'culturefeed_uitpas.loaders.inc';
require_once 'culturefeed_uitpas.menu.inc';
require_once 'culturefeed_uitpas.profile.inc';
require_once 'culturefeed_uitpas.theme.inc';

/**
 * Module implements hook_culturefeed_login_redirect_destination_alter().
 */
function culturefeed_uitpas_culturefeed_login_redirect_destination_alter(&$destination) {

  if (isset($_GET['isnewpassholder'])) {
    
    $uitpas_user = culturefeed_uitpas_get_uitpas_user();
  
    // User is registered so we clear cache
    cache_clear_all('culturefeed:uitpas:passholder:' . $uitpas_user->user->id, 'cache_culturefeed');
    cache_clear_all('culturefeed:uitpas:passholders:' . $uitpas_user->user->mbox, 'cache_culturefeed');
    
    $destination = 'culturefeed/profile/edit';
  }

}

/**
 * Implements hook_ctools_plugin_directory().
 */
function culturefeed_uitpas_ctools_plugin_directory($module, $plugin) {
  return 'ctools/plugins/' . $plugin;
}

/**
 * Implements hook_views_api().
 */
function culturefeed_uitpas_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'culturefeed_uitpas') . '/views',
  );
}

/**
 * Implements hook_culturefeed_ui_profile_box_dropdown_items().
 */
function culturefeed_uitpas_culturefeed_ui_profile_box_dropdown_items(CultureFeed_User $cf_account) {



  if (culturefeed_uitpas_is_passholder()) {

    $items['uitpas-divider'] = array(
      'data' => '',
      'class' => 'divider',
      'weight' => 9,
    );

    $items['my-uitpas'] = array(
      'data' => l(t('My UiTPAS'), 'culturefeed/profile/uitpas'),
      'class' => 'my-uitpas',
      'weight' => 10,
    );

    $items['uitpas-advantages'] = array(
      'data' => l(t('My promotions'), 'culturefeed/profile/uitpas/promotions'),
      'class' => 'uitpas-advantages',
      'weight' => 11,
    );

    $items['uitpas-history'] = array(
      'data' => l(t('Points history'), 'culturefeed/profile/uitpas/actions'),
      'class' => 'uitpas-history',
      'weight' => 12,
    );

    return $items;

  }

  else {

    if (culturefeed_uitpas_not_yet_registered()) {

      $items['uitpas-divider'] = array(
        'data' => '',
        'class' => 'divider',
        'weight' => 9,
      );

      $items['uitpas-register'] = array(
        'data' => l(t('Register your UiTPAS'), 'register_uitpas'),
        'class' => 'uitpas-register',
        'weight' => 10,
      );

      return $items;
    }

  }

}

/**
 * Implements hook_init().
 */
function culturefeed_uitpas_init() {
  if (!in_array(current_path(), array('culturefeed/uitpas/reminder/toggle', 'register_uitpas')) &&
      variable_get('culturefeed_uitpas_remind_user_without_uitpas', 1)) {

    $current_state = isset($_COOKIE['Drupal_visitor_culturefeed_uitpas_reminder']) ? $_COOKIE['Drupal_visitor_culturefeed_uitpas_reminder'] : 'on';

    // Don't do anything when reminder was toggled off with cookie.
    if ($current_state !== 'on') {
      return;
    }

    if (culturefeed_uitpas_not_yet_registered()) {
      $message = t('You have successfully logged in, but you did not register your UiTPAS yet. Fill in the <a href="@register_url">necessary information</a> to consult your benefits and points balance. <a href="@toggle_url">Do not show this message again</a>.');
      $args = array(
        '@register_url' => url('register_uitpas'),
        '@toggle_url' => url('culturefeed/uitpas/reminder/toggle'),
      );
      $message = format_string($message, $args);
      drupal_set_message($message, 'warning', FALSE);
    }
  }
}
