<?php

module_load_include('inc', 'entry_api_ui', 'includes/entry_api_ui.helpers');

/**
 * Implements hook_permission().
 */
function entry_api_ui_permission() {
  return array(
    'manage object tags' => array(
      'title' => t('Manage object tags'),
      'description' => t('Manage all the tags from the objects on culturefeed (events, actors, ...).'),
    ),
    'manage lifestyle profile tags' => array(
      'title' => t('Manage lifestyle profile tags'),
      'description' => t('Manage the lifestyle profile tags from the objects on culturefeed (events, actors, ...).'),
    ),
    'create culturefeed events' => array(
      'title' => t('Create events'),
      'description' => t('Create new events through the entity api.'),
    ),
    'edit culturefeed events' => array(
      'title' => t('Edit events'),
      'description' => t('Edit events through the entity api.'),
    ),
    'delete culturefeed events' => array(
      'title' => t('Delete events'),
      'description' => t('Delete events through the entity api.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function entry_api_ui_menu() {

  $items = array();

  $items['entryapi/event/%entry_api_event/tags'] = array(
    'title' => 'Tags',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('entry_api_ui_edit_tags_form', 2),
    'access callback' => 'entry_api_ui_manage_tags_access',
    'file' => 'includes/entry_api_ui.pages.inc',
  );

  $items['entryapi/event/add'] = array(
    'title' => 'Event toegevoegen',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('entry_api_ui_event_form'),
    'access arguments' => array('create culturefeed events'),
    'file' => 'includes/entry_api_ui.pages.inc',
  );

  $items['entryapi/event/%entry_api_event/edit'] = array(
    'title' => 'Event aanpassen',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('entry_api_ui_event_form', 2),
    'access arguments' => array('edit culturefeed events'),
    'file' => 'includes/entry_api_ui.pages.inc',
  );

  $items['entryapi/event/%entry_api_event/delete'] = array(
    'title' => 'Event verwijderen',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('entry_api_ui_delete_event_form', 2),
    'access arguments' => array('delete culturefeed events'),
    'file' => 'includes/entry_api_ui.pages.inc',
  );

  $items['entryapi'] = array(
    'title' => 'entryapi',
    'page callback' => 'entry_api_ui_page',
    'access callback' => TRUE
  );

  return $items;

}

/**
 * Load an event on the entry api.
 */
function entry_api_event_load($id) {

  try {
    return DrupalCultureFeed_EntryApi::getEvent($id);
  }
  catch (Exception $e) {
    watchdog_exception(WATCHDOG_ERROR, $e);
  }

  return FALSE;

}

/**
 * Access callback, to check if a user has access to the manage tags screen.
 */
function entry_api_ui_manage_tags_access() {
  return user_access('manage lifestyle profile tags') || user_access('manage object tags');
}

function entry_api_ui_page() {

  $event = new CultureFeed_Cdb_Event();

  // Exceptions
  $exceptions = new CultureFeed_Cdb_Calendar_Exceptions();
  $exception = new CultureFeed_Cdb_Calendar_Timestamp('2012-11-10');
  $exception->setOpenType(CultureFeed_Cdb_Calendar::OPEN_TYPE_BYAPPOINTMENT);
  $exceptions->add($exception);

  $exception = new CultureFeed_Cdb_Calendar_Timestamp('2012-11-11');
  $exception->setOpenType(CultureFeed_Cdb_Calendar::OPEN_TYPE_CLOSED);
  $exceptions->add($exception);

  // Weekscheme
  $weekscheme = new CultureFeed_Cdb_Calendar_Weekscheme();

  $monday = new CultureFeed_Cdb_Calendar_SchemeDay('monday', CultureFeed_Cdb_Calendar::OPEN_TYPE_OPEN);
  $monday->setOpenFrom('20:00:00');
  $monday->setOpenTill('22:00:00');
  $weekscheme->setDay('monday', $monday);

  $tuesday = new CultureFeed_Cdb_Calendar_SchemeDay('tuesday', CultureFeed_Cdb_Calendar::OPEN_TYPE_BYAPPOINTMENT);
  $weekscheme->setDay('tuesday', $tuesday);

  $wednesday = new CultureFeed_Cdb_Calendar_SchemeDay('wednesday', CultureFeed_Cdb_Calendar::OPEN_TYPE_CLOSED);
  $weekscheme->setDay('wednesday', $wednesday);

  $thursday = new CultureFeed_Cdb_Calendar_SchemeDay('thursday', CultureFeed_Cdb_Calendar::OPEN_TYPE_CLOSED);
  $weekscheme->setDay('thursday', $thursday);

  $friday = new CultureFeed_Cdb_Calendar_SchemeDay('friday', CultureFeed_Cdb_Calendar::OPEN_TYPE_CLOSED);
  $weekscheme->setDay('friday', $friday);

  $saturday = new CultureFeed_Cdb_Calendar_SchemeDay('saturday', CultureFeed_Cdb_Calendar::OPEN_TYPE_CLOSED);
  $weekscheme->setDay('saturday', $saturday);

  $sunday = new CultureFeed_Cdb_Calendar_SchemeDay('sunday', CultureFeed_Cdb_Calendar::OPEN_TYPE_CLOSED);
  $weekscheme->setDay('sunday', $sunday);

  // Calendar details.

  // Timestamps calendar.
  /*$calendar = new CultureFeed_Cdb_Calendar_TimestampList();
  $calendar->add(new CultureFeed_Cdb_Calendar_Timestamp('2012-10-09', '20:00:00+01:00'));
  $calendar->add(new CultureFeed_Cdb_Calendar_Timestamp('2009-12-02', '21:00:00+01:00'));*/

  // Periods calendar.
  /*$calendar = new CultureFeed_Cdb_Calendar_PeriodList();
  $period = new CultureFeed_Cdb_Calendar_Period('2012-10-09', '2012-12-09');
  $period->setWeekScheme($weekscheme);
  $period->setExceptions($exceptions);
  $calendar->add($period);*/

  // Permanent
  $calendar = new CultureFeed_Cdb_Calendar_Permanent();
  $calendar->setWeekScheme($weekscheme);
  $calendar->setExceptions($exceptions);

  $event->setCalendar($calendar);

  // Categories.
  $categories = new CultureFeed_Cdb_CategoryList();
  $categories->add(new Culturefeed_Cdb_Category(Culturefeed_Cdb_Category::CATEGORY_TYPE_EVENT_TYPE, '0.50.4.0.0', 'Concert'));
  $categories->add(new Culturefeed_Cdb_Category(Culturefeed_Cdb_Category::CATEGORY_TYPE_THEME, '1.8.1.0.0', 'Klassieke muziek'));
  $categories->add(new Culturefeed_Cdb_Category(Culturefeed_Cdb_Category::CATEGORY_TYPE_PUBLICSCOPE, '6.4.0.0.0', 'Internationaal'));
  $event->setCategories($categories);

  // Contact info.
  $contact = new CultureFeed_Cdb_ContactInfo();

  // Address.
  $physical_address = new CultureFeed_Cdb_PhysicalAddress();
  $physical_address->setCity('Brussel');
  $physical_address->setCountry('BE');
  $physical_address->setHouseNumber(110);
  $physical_address->setStreet('Anspachlaan');
  $physical_address->setZip(1000);
  $physical_address->setGeoInformation(new CultureFeed_Cdb_GeoInformation(4.348676, 50.847406));
  $contact->addAddress(new CultureFeed_Cdb_Address($physical_address));

  // Other contact info.
  $contact->addMail(new CultureFeed_Cdb_Mail('info@abconcerts.be', FALSE, FALSE));
  $contact->addPhone(new CultureFeed_Cdb_Phone('02-548.24.84', CultureFeed_Cdb_Phone::PHONE_TYPE_PHONE, FALSE, FALSE));
  $contact->addPhone(new CultureFeed_Cdb_Phone('02-548.24.24', CultureFeed_Cdb_Phone::PHONE_TYPE_PHONE, FALSE, TRUE));
  $contact->addUrl(new CultureFeed_Cdb_Url('http://www.abconcerts.be', TRUE, FALSE));

  $event->setContactInfo($contact);

  // Event details.
  $detail = new Culturefeed_Cdb_EventDetail();
  $detail->setTitle('title');
  $detail->setShortDescription('description');
  $detail->setLanguage('nl');

  $details = new CultureFeed_Cdb_EventDetailList();
  $details->add($detail);
  $event->setDetails($details);

  // Location (with same physical address).
  $address = new CultureFeed_Cdb_Address($physical_address);
  $location = new CultureFeed_Cdb_Location($address);
  $location->setLabel('jco_test_api_01_location_label xxxxx');
  $event->setLocation($location);

  try {

    // Create event.
    //$link = DrupalCultureFeed_EntryApi::createEvent($event);
    //debug($link);

    // Update an event.
    //$event->setExternalId('cc83f911-2ad7-47c5-8bf3-14de3397099c');

    /*$test = $event->getDetails()->current()->setTitle('another new title');
    DrupalCultureFeed_EntryApi::updateEvent($event);*/

    // Add tags to the event.
    //DrupalCultureFeed_EntryApi::addTagToEvent($event, array('tag2', 'tag3'));

    // Remove a tag from the event.
    //DrupalCultureFeed_EntryApi::removeTagFromEvent($event, 'destoop');

    // Delete an event.
    //DrupalCultureFeed_EntryApi::deleteEvent($id);

    // Get the event.
    //DrupalCultureFeed_EntryApi::getEvent('cc83f911-2ad7-47c5-8bf3-14de3397099c');
  }
  catch (Exception $e) {
    return $e->getMessage();
  }

  return '';

}