<?php
/**
 * @file
 * Performs searches to the Cultuurnet api.
 * 
 * @todo 
 * - Remove the searchpoc helper functions
 * - Fix the function searchpoc_activity_recommend_link so that the function
 *   "culturefeed_ui_block_users_recommends_config" is moved to correct place 
 * - check if it wouldn't be better to just use the convenience of 
 *   culturefeed_agenda > culturefeed_search_ui. This way the search ui can declare 
 *   the searchable types, it can have the search block, the sortorder block/functions, ...
 * -
 * 
 */

module_load_include('inc', 'culturefeed_agenda', 'includes/helpers');

/**
 * Implements hook_theme().
 */
function culturefeed_agenda_theme() {

  $path = drupal_get_path('module', 'culturefeed_agenda') . '/theme';

  return array(
    'culturefeed_event_summary' => array(
      'variables' => array('item' => NULL),
      'template' => 'culturefeed-event-summary',
      'path' => $path,
      'file' => 'theme.inc',
    ),
    'culturefeed_event' => array(
      'variables' => array('item' => NULL),
      'template' => 'culturefeed-event',
      'path' => $path,
      'file' => 'theme.inc',
    ),

    'culturefeed_search_page' => array(
      'variables' => array('searchresult' => NULL, 'sortorder_form' => NULL),
      'template' => 'culturefeed-search-page',
      'path' => $path,
      'file' => 'theme.inc',
    ),
    'culturefeed_search_facets_list' => array(
      'variables' => array(
        'facet' => NULL, 'path' => NULL, 'query' => NULL,
      ),
      'path' => $path,
      'file' => 'theme.inc',
    ),
    'culturefeed_search_facet' => array(
      'variables' => array(
        'name' => NULL,
        'count' => 0,
        'active' => FALSE,
        'url' => NULL,
      ),
      'template' => 'culturefeed-search-facet',
      'path' => $path,
      'file' => 'theme.inc',
    ),
    
    // @todo check where to merge this with (item or event?)
    'culturefeed_searchresult_item' => array(
      'variables' => array('item' => NULL),
      'template' => 'culturefeed-searchresult-item',
    ),
  );

}

/**
 * Implements hook_menu().
 */
function culturefeed_agenda_menu() {

  $items = array();

  // Menu path for search.
  $items['agenda/search'] = array(
    'title' => 'Agenda',
    'page callback' => 'culturefeed_agenda_search_page',
    //'page arguments' => array(''),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  // Menu path for detail pages.
  $items['agenda/a/%/%culturefeed_agenda_actor'] = array(
    'title callback' => 'culturefeed_agenda_detail_title',
    'title arguments' => array(3),
    'page callback' => 'culturefeed_agenda_detail_page',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  $items['agenda/e/%/%culturefeed_agenda_event'] = array(
    'title callback' => 'culturefeed_ui_agenda_detail_title',
    'title arguments' => array(3),
    'page callback' => 'culturefeed_agenda_detail_page',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  $items['agenda/p/%/%culturefeed_agenda_production'] = array(
    'title callback' => 'culturefeed_agenda_detail_title',
    'title arguments' => array(3),
    'page callback' => 'culturefeed_agenda_detail_page',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  return $items;

}

/**
 * Implements hook_block_info().
 */
function culturefeed_agenda_block_info() {
  $blocks = array();

  $blocks['culturefeed-search-box'] = array(
    'info' => t('Culturefeed search: search box'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['culturefeed-search-sortorder'] = array(
    'info' => t('Culturefeed search: sort order filter'),
    'cache' => DRUPAL_CACHE_PER_USER,
  );

  $blocks['culturefeed-search-facets'] = array(
    'info' => t('Culturefeed search: search facets'),
    'cache' => DRUPAL_CACHE_PER_USER,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function culturefeed_agenda_block_view($delta) {

  $block = array();
  
  switch ($delta) {

    case 'culturefeed-search-box':
      $block['subject'] = '';
      module_load_include('inc', 'culturefeed_agenda', 'includes/blocks');
      $block['content'] = drupal_get_form('culturefeed_agenda_search_block_form');
      break;
      
    case 'culturefeed-search-sortorder':
      $block['subject'] = '';
      module_load_include('inc', 'culturefeed_agenda', 'includes/blocks');
      $block['content'] = drupal_get_form('culturefeed_agenda_search_sortorder_form');
      break;
      
    case 'culturefeed-search-facets':
      $block['subject'] = '';
      module_load_include('inc', 'culturefeed_agenda', 'includes/blocks');
      $block['content'] = culturefeed_agenda_search_facets_block();
      break;

    default:
  }
  
  return $block;

}

/**
 * Implements hook_culturefeed_search_type_info().
 */
function culturefeed_agenda_culturefeed_search_type_info() {
  return array(
    'activiteiten' => array(
      'path' => 'agenda/search',
      'title' => 'Activiteiten',
    ),
  );
}

/**
 * Load an event from the api.
 */
function culturefeed_agenda_event_load($cdb_id) {
  return culturefeed_search_item_load($cdb_id);
}

/**
 * Load an actor from the api.
 */
function culturefeed_agenda_actor_load($cdb_id) {
  return culturefeed_search_item_load($cdb_id);
}

/**
 * Load a production from the api.
 */
function culturefeed_agenda_production_load($cdb_id) {
  return culturefeed_search_item_load($cdb_id);
}
