<?php
/**
 * @file
 * Performs searches to the Cultuurnet api.
 */

module_load_include('inc', 'culturefeed_agenda', 'includes/helpers');

/**
 * Implements hook_menu().
 */
function culturefeed_agenda_menu() {
  
  $items = array();
  
  $items['agenda/s'] = array(
    'title' => 'Uitgebreid zoeken',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('culturefeed_agenda_advanced_search_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function culturefeed_agenda_block_info() {
  $blocks = array();
  
  $blocks['advanced-search'] = array(
    'info' => t('Advanced search field'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function culturefeed_agenda_block_view($delta) {

  //$query = drupal_get_query_parameters();
  dsm($delta);
  switch ($delta) {
    
    case 'advanced-search':
      $block['subject'] = '';
      module_load_include('inc', 'culturefeed_agenda', 'includes/blocks');
      $block['content'] = drupal_get_form('culturefeed_agenda_block_form');
      return $block;
      break;
      
    default:
  }
  
}
