<?php
/**
 * @file
 * Performs searches to the Cultuurnet api.
 * 
 * @todo 
 * - Remove the searchpoc helper functions
 * - Fix the function searchpoc_activity_recommend_link so that the function
 *   "culturefeed_ui_block_users_recommends_config" is moved to correct place 
 * 
 */

module_load_include('inc', 'culturefeed_agenda', 'includes/helpers');

/**
 * Implements hook_menu().
 */
function culturefeed_agenda_menu() {
  
  $items = array();
  
  $items['agenda/search'] = array(
    'title' => 'Agenda',
    'page callback' => 'culturefeed_agenda_search_page',
    //'page arguments' => array(''),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function culturefeed_agenda_theme() {
  return array(
    'culturefeed_search_page' => array(
      'variables' => array('searchresult' => NULL),
      'template' => 'culturefeed-search-page',
    ),
    'culturefeed_searchresult_item' => array(
      'variables' => array('item' => NULL),
      'template' => 'culturefeed-searchresult-item',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function culturefeed_agenda_block_info() {
  $blocks = array();
  
  $blocks['advanced-search'] = array(
    'info' => t('Advanced search field'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function culturefeed_agenda_block_view($delta) {

  //$query = drupal_get_query_parameters();
  dsm($delta);
  switch ($delta) {
    
    case 'advanced-search':
      $block['subject'] = '';
      module_load_include('inc', 'culturefeed_agenda', 'includes/blocks');
      $block['content'] = drupal_get_form('culturefeed_agenda_block_form');
      return $block;
      break;
      
    default:
  }
  
}

/**
 * Preprocess function for the search page main section.
 * 
 * @param array $vars
 */
function culturefeed_agenda_culturefeed_search_page_preprocess(&$vars) {
  dsm($vars);
}
