<?php

/**
 * @file
 * The culturefeed udb3 module file.
 */

/**
 * Implements hook_cache_flush().
 */
function culturefeed_udb3_cache_flush() {

  // Delete the domain message implementations.
  $entities = array('event_store', 'organizer_store', 'place_store', 'used_keywords_memory_event_store');

  foreach ($entities as $entity_type) {
    $results = entity_load_multiple($entity_type);
    $entity_ids = array_keys($results);
    entity_delete_multiple($entity_type, $entity_ids);
  }

}
