<?php
/**
 * @file
 * CultureFeed Pages makes it possible to view / manage pages.
 */

module_load_include('inc', 'culturefeed_pages', 'includes/helpers');

/**
 * Implements hook_permission().
 */
function culturefeed_pages_permission() {

  return array(
    'join culturefeed page' => array(
      'title' => t('Join a culturefeed page'),
    ),
  );

}

/**
 * Implements hook_theme().
 */
function culturefeed_pages_theme() {

  $path = drupal_get_path('module', 'culturefeed_pages') . '/theme';

  return array(

    'culturefeed_pages_join_page' => array(
      'variables' => array(
        'form' => NULL,
        'result' => NULL,
        'search' => '',
      ),
      'path' => $path,
      'file' => 'theme.inc',
      'template' => 'culturefeed-pages-join-page',
    ),

    'culturfeed_pages_join_search_result_item' => array(
      'variables' => array('item' => NULL),
      'path' => $path,
      'file' => 'theme.inc',
      'template' => 'culturefeed-pages-join-search-result-item',
    ),

    'culturefeed_pages_fellow_members_block' => array(
      'variables' => array(
        'account' => NULL,
        'page' => NULL,
        'members' => array(),
      ),
      'path' => $path,
      'file' => 'theme.inc',
      'template' => 'culturefeed-pages-fellow-members-block',
    ),

    'culturefeed_pages_following_pages_block' => array(
      'variables' => array('following' => array()),
      'path' => $path,
      'file' => 'theme.inc',
    ),

  );

}

/**
 * Implements hook_menu().
 */
function culturefeed_pages_menu() {

  $items = array();

  $items['pages/join'] = array(
    'title callback' => 'culturefeed_pages_join_title',
    'page callback' => 'culturefeed_pages_join_page_search',
    'access arguments' => array('join culturefeed page'),
    'file' => 'includes/pages.inc',
  );

  /*$items['agenda/p/%/%culturefeed_agenda_production'] = array(
    'title callback' => 'culturefeed_agenda_detail_title',
    'title arguments' => array(3),
    'page callback' => 'culturefeed_agenda_detail_page',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );*/

  $items['ajax/culturefeed/pages/page-suggestion'] = array(
    'page callback' => 'culturefeed_pages_page_suggestion_autocomplete_page',
    'page arguments' => array(4),
    'access arguments' => array('join culturefeed page'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  $items['culturefeed/pages/join/%/%culturefeed_pages_page'] = array(
    'page callback' => 'culturefeed_pages_page_join',
    'page arguments' => array(3, 4),
    'access arguments' => array('join culturefeed page'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/pages.inc',
  );

  return $items;

}

/**
 * Implements hook_block_info().
 */
function culturefeed_pages_block_info() {

  $blocks = array();

  $blocks['user-fellow-members'] = array(
    'info' => t('Fellow members from user'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['pages-user-follows'] = array(
    'info' => t("Pages i'm following"),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;

}

/**
 * Implements hook_block_view().
 */
function culturefeed_pages_block_view($delta) {

  module_load_include('inc', 'culturefeed_pages', 'includes/blocks');

  switch ($delta) {

    case 'user-fellow-members':
      $account = menu_get_object('user');
      return culturefeed_pages_block_fellow_members($account);

    case 'pages-user-follows':
      $account = menu_get_object('user');
      return culturefeed_pages_block_pages_user_follows($account);
    break;

  }

}

/**
 * Load a culturefeed page.
 */
function culturefeed_pages_page_load($id) {

  try {

    $cf_pages = DrupalCultureFeed::getConsumerInstance()->pages();
    return $cf_pages->getPage($id);

  }
  catch (Exception $e) {
    watchdog_exception('culturefeed_pages', $e);
  }

  return FALSE;

}

/**
 * Title callback for the join page.
 */
function culturefeed_pages_join_title() {
  return format_string('Jouw pagina op @sitename', array('@sitename' => variable_get('site_name')));
}