<?php

/**
 * Implements hook_theme().
 */
function culturefeed_udb3_app_theme() {
  return array(
    'udb3_search' => array(
      'render element' => 'elements',
    ),
    'udb3_landing' => array(
      'render element' => 'elements',
    ),
    'page' => array(
      'render element' => 'elements',
    ),
    'udb3_new_event_form' => array(),
  );
}

/**
 * Implements hook_page_attachments().
 */
function culturefeed_udb3_app_page_attachments(array &$page) {
  $udb3AppSettings = Drupal::config('culturefeed_udb3_app.settings');

  /** @var \Drupal\Core\Routing\UrlGeneratorInterface $urlGenerator */
  $urlGenerator = Drupal::service('url_generator');

  /** @var \Drupal\Core\Utility\UnroutedUrlAssemblerInterface $unroutedUrlAssembler */
  $unroutedUrlAssembler = Drupal::service('unrouted_url_assembler');

  $apiPath = $unroutedUrlAssembler->assemble(
    'base://udb3/api/1.0/',
    array('absolute' => TRUE)
  );

  $page['#attached']['drupalSettings']['culturefeed_udb3_app']['appConfig'] = [
    'baseUrl' => $apiPath,
    'baseApiUrl' => $apiPath,
    'authUrl' => $urlGenerator->generateFromRoute(
      'culturefeed.oauth.connect',
      array(),
      array('absolute' => TRUE)
    ),
    'socketUrl' => $udb3AppSettings->get('websocket_server')
  ];
}
